name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create .env file
      run: |
        echo "BASE_URL=https://opensource-demo.orangehrmlive.com/" >> .env
        echo "USERNAME=Admin" >> .env
        echo "PASSWORD=admin123" >> .env
    
    - name: Run Cypress tests
      run: npm run cypress:report
    
    - name: Generate HTML report
      if: always()
      run: npx marge cy-report/mochawesome.json --reportDir cy-report --inline
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-test-results
        path: |
          cy-report/
          cypress/screenshots/
          cypress/videos/
        retention-days: 30
    
    - name: Upload HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mochawesome-report
        path: cy-report/mochawesome.html
        retention-days: 30